#This is name of workflow
name: Hello

#runs on a tigger
on:
  push:
    branches:[main]
#These are job inside the workflow
jobs:

  #this is name of job
  greet: 
      #this is github runner, each jpb runs on runner
      runs-on: ubuntu-latest
      steps:
          - name: say hello to users
            run: echo "Hello dosto"

          - name: say hello to user name
            run: echo "Hello $USER"
          
          
